### ISSUE TITLE
For non-admins, limit container transfer to reciprocated friendships

### ISSUE THREAD

**Issue by mrclay** [ColdTrick/entity_tools#2]
Ideally non-admin users would need to receive permission from the new owner: E.g. Fred wants to send a page to Wilma. Fred fills out the (current) transfer form. The system sends Wilma a transfer request notification. Wilma can then approve the single request, and optionally add Fred to her whitelist. Fred then receives a confirmation notification and can transfer the item with one click (the details of the transfer were stored).

Requiring a reciprocated friendship would be easy for now. 

It also doesn't look like the same limitations are applied during the action as are in place in the UI. E.g. can I tamper the form to transfer to any user?

**Comment by jdalsem** [comment]
Closing as this plugin is not intended for non-admins
