### ISSUE TITLE
jqueryui-timepicker-addon/dist does not exists in elgg vendor folder

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/entity_tools#7]
opendir(/home/username/public_html/vendor/bower-asset/jqueryui-timepicker-addon/dist): failed to open dir: No such file or directory

https://github.com/ColdTrick/entity_tools/blob/8702490d0ffa0de6b0643f7d28970c92c8e05309/elgg-plugin.php#L39

**Comment by jeabakker** [comment]
Did you use a community release or composer install or github download

**Comment by rohit1290** [comment]
community release

**Comment by jeabakker** [comment]
did you use the github zip or the extra `entity-tools_v5.0.zip` because the github `source` zip doesn't contain composer dependencies

**Comment by rohit1290** [comment]
ok, source zip did not had the dependencies. 

I downloaded the entity_tools_v5.0.zip just above the source zip. That zip file has the dependencies.
