### ISSUE TITLE
No content to edit on elgg 4.3

### ISSUE THREAD

**Issue by Arnaud-Magous** [ColdTrick/entity_tools#8]
**Elgg version**
4.3

**Plugin version**
8.0

**Plugin source**
- Github releases download

**Describe the bug**
When I go to Admin > Tools > Manage Content, the component can't find any content to edit as you can see :
![snapshot](https://user-images.githubusercontent.com/91007731/210392402-51bb7c44-7776-4fb7-ab99-7f93978444dd.png)

Of course, there are actually a few blog posts, so I should be able to see them.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jdalsem** [comment]
If you go to that specific link you will find all content owned by the site... that might not be any content. Mostly blogs are owned by a person/user, so you need to go to the user whos content you want to manage. For example on their profile you might find a link (top right dropdown) to manage their content. Please let me know if that was the case.

**Comment by Arnaud-Magous** [comment]
Indeed, that was the problem, thx a lot for your help !  

I think you should mention that point in the plugin doc cause that was not obvious for me ...

**Comment by Arnaud-Magous** [comment]
Well, another issue now : can't edit the date of a post.  The field is there, but it is not editable :(
![snap2](https://user-images.githubusercontent.com/91007731/210720696-377100d4-426a-4370-b47a-16e75a2f618a.png)

I can highlight the date but not edit it ...  (I can edit the other fields)

**Comment by jdalsem** [comment]
The datepicker is a custom javascript dependency. Did you install the compiled ZIP download from the github releases or just the source code? You can also check your developer tools in your browser to see if there are some issues/warnings.

**Comment by Arnaud-Magous** [comment]
I installed the compiled ZIP downloaded from github, yes.  

The textfield seems is actually 'readonly" so I can't edit it : 

![snap2](https://user-images.githubusercontent.com/91007731/210986646-46248a2b-de07-4568-9c15-1ffa225e2f4e.png)

But anyway, if I change it to writable, I can make the changes, the site warns me "Are you sure ?", the page refreshes and then ... nothing appens, it's back to the former value.

**Comment by Arnaud-Magous** [comment]
OK, found something in the console : 
`GEThttp://[mysite]/mymemory/cache/1673000448/default/jquery-datetimepicker/jquery.datetimepicker.min.css
[HTTP/1.1 403 Forbidden 1133ms]

GEThttp://[mysite]/mymemory/cache/1673000448/default/jquery-datetimepicker/jquery.datetimepicker.full.min.js
[HTTP/1.1 403 Forbidden 217ms]

Uncaught Error: Script error for "jquery-datetimepicker/jquery.datetimepicker.full.min", needed by: input/datetimepicker
https://requirejs.org/docs/errors.html#scripterror`

Allright, I have to investigate but it seems that I don't have the rights to access the js file ... I don't understand why cause the page can access to all other css or js files ???

**Comment by Arnaud-Magous** [comment]
Indeed, there is no "cache" folder at this path ... Where is the cache directory in elgg ?

**Comment by jdalsem** [comment]
If there is no cacheroot configured in your settings.php it will make a cache folder in the dataroot folder. 

You can also try to invalidate the cache on /admin (big button top right). That will force a regeneration of the cache files.

**Comment by Arnaud-Magous** [comment]
OK, thx for your advises.  I successfully changed the cache directory to /[myelggrootdir]/cache/ and I can see that elgg has put in this directory the cache files.

But entity-tools continues to complain about missing datetimepicker : 
`Uncaught Error: Script error for "jquery-datetimepicker/jquery.datetimepicker.full.min", needed by: input/datetimepicker
https://requirejs.org/docs/errors.html#scripterror
    makeError http://[mysite]/mymemory/cache/1673431661/default/require.js:22
    onScriptError http://[mysite]/mymemory/cache/1673431661/default/require.js:118
[require.js:22:53](http://[mysite]/mymemory/cache/1673431661/default/require.js)
    makeError http://[mysite]/mymemory/cache/1673431661/default/require.js:22
    onScriptError http://[mysite]/mymemory/cache/1673431661/default/require.js:118`

I can't see anywhere this "1673431661" directory under /cache/ ... What does this mean ?  Do I need to set another parameter somewhere else ?

TIA for your help !

**Comment by jdalsem** [comment]
can you confirm that there is a vendor folder in the plugin? it should be at 'mod/entity_tools/vendor'

**Comment by Arnaud-Magous** [comment]
No vendor folder in the plugin ...

![snap3](https://user-images.githubusercontent.com/91007731/212074927-80f00126-3b9b-4957-a487-6199024543ef.png)

**Comment by Arnaud-Magous** [comment]
But there is one in the main folder :

![snap4](https://user-images.githubusercontent.com/91007731/212075390-9e4508d9-131e-4c7d-b774-4578ec022c57.png)

**Comment by jdalsem** [comment]
then you did not download the correct zip from the releases... [entity_tools_v8.0.zip](https://github.com/ColdTrick/entity_tools/releases/download/v8.0/entity_tools_v8.0.zip) contains a vendor folder which contains the datetimepicker vendor files you need

**Comment by Arnaud-Magous** [comment]
Allright, I understand my mistake now : I downloaded the source code, I was wrong (and I didn't understand your previous question, sorry, it was not the "asset" ZIP that I downloaded, but a ZIP containing only the source code).

So, it works like a charm now, thx again for all your help !!!
