### ISSUE TITLE
Error in Elgg 6.1.0 - jquery-datetimepicker

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/entity_tools#9]
https://github.com/ColdTrick/entity_tools/blob/9a02b7b9da6c6ad8346217f30a9cb7c0129a23a3/elgg-plugin.php#L68

Getting the following error in Elgg 6.1.0

`ELGG.ERROR: RecursiveDirectoryIterator::__construct(/path/to/elgg6/vendor/npm-asset/jquery-datetimepicker/build/): Failed to open directory: No such file or directory`

**Comment by jeabakker** [comment]
we haven't had time to look into our plugins on Elgg 6.1.

So thanks for reporting

**Comment by jeabakker** [comment]
How did you install entity_tools?
- Git clone
- Git download
- ZIP download from community

It looks like you didn't do a `composer install` in the entity_tools directory. This isn't needed if you did a `composer require coldtrick/entity_tools` in the Elgg project root.

**Comment by rohit1290** [comment]
I installed it using git clone. When I was on 6.0.7, it did not give this error, but it started appearing in the error log after I upgraded to 6.1.0. 

I just ran "composer install" in the plugin directory, and everything is working fine now with no errors.
